version: '2'
services:

  example:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/var/www/html
  db:
    image: mysql
    restart: always
    command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
